
package ua.nure.petryasya.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MovieService", targetNamespace = "http://service.petryasya.nure.ua/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MovieService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.petryasya.nure.ua/MovieService/addMovieRequest", output = "http://service.petryasya.nure.ua/MovieService/addMovieResponse")
    public void addMovie(
            @WebParam(name = "arg0", partName = "arg0")
            Movie arg0);

    /**
     * 
     * @return
     *     returns client.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.petryasya.nure.ua/MovieService/getMoviesRequest", output = "http://service.petryasya.nure.ua/MovieService/getMoviesResponse")
    public ArrayList getMovies();

    /**
     * 
     * @param arg0
     * @return
     *     returns client.Movie
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.petryasya.nure.ua/MovieService/getMovieRequest", output = "http://service.petryasya.nure.ua/MovieService/getMovieResponse")
    public Movie getMovie(
            @WebParam(name = "arg0", partName = "arg0")
            int arg0);

}
